apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  policy.default: role:admin
  server.insecure: "true"
  server.metrics.enabled: "true"
  reposerver.disable.tls: "true"
  dexserver.disable.tls: "true"
  server.repo.server.plaintext: "true"
  controller.repo.server.plaintext: "true"
  #server.basehref: "/argocd-server"
  server.rootpath: "/argocd-server"
  resource.customizations.health.argoproj.io_Application: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs  