apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kube.local`) && (PathPrefix(`/argocd-server`))
      kind: Rule
      services:
      - name: argocd-server
        port: 80
        namespace: argocd
    - kind: Rule
      match: Host(`kube.local`) && (PathPrefix(`/argocd-server`)) && Headers(`Content-Type`, `application/grpc`)
      services:
      - name: argocd-server
        port: 80
        scheme: h2c
  tls: